# Generated by Django 5.2.17 on 2026-09-08 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=80, verbose_name='Imię lub pseudonim')),
                ('location', models.CharField(blank=True, default='', max_length=120, verbose_name='Miejscowość')),
                ('desired_role', models.CharField(blank=True, default='', max_length=120, verbose_name='Jakiej pracy szukasz?')),
                ('career_goal', models.TextField(blank=True, default='', max_length=1000, verbose_name='Twój cel zawodowy')),
                ('revision', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'prywatny szkic profilu pracownika',
                'verbose_name_plural': 'prywatne szkice profili pracowników',
                'constraints': [models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='profile_revision_positive')],
            },
        ),
    ]
